version: "3.1"

services:
  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    command: postgres -c 'shared_buffers=256MB' -c 'max_connections=200'
  # api:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   env_file: .env
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
